### PR TITLE
Split Signup into separate steps for email verification and account creation

### PR DESCRIPTION
**Pull request by tiwari-abhishek**
The default Signup page clubs together the email verification controls, followed by user's First Name, Last Name and other fields. 

2020-05-12_19h19_39

This may not always be desirable since the users cannot interact with these fields without verifying their email anyway. Ideal user experience would be to split the registration process into two separate screens, where the users only see the email verification related controls first, and not the entire set of Registration controls. When they complete the email verification, they should be taken to the next screen which asks for more user attributes (firstname, lastname, dob etc.).This sample splits the default signup behaviour into two separate steps. First step performs Email Verification only, avoiding all other default fields related to users registration. Second step (if email verification was successful) takes the users to a new screen where they can actually create their accounts.

flow

### CODE REVIEW

**Comment by JasSuri** [comment]
Thanks, great addition. Is it possible to modify the sample to chain from the TrustFrameworkExtensions file instead of from the TrustFrameworkBase file of the starter pack?

**Comment by tiwari-abhishek** [comment]
Thank you. Actually I had to leave a reference to the base policy because there is a dependency on the default "Email" claim that comes from the TrustFrameworkBase.xml. I added the TrustFrameworkBase.xml for completeness sake so that the policy becomes standalone. I hope that is fine?

**Comment by JasSuri** [comment]
The pre req is to have the starter pack installed into the tenant, which should contain all other dependancies for your sample file to chain to. So you should set basePolicy to TrustFrameworkExtensions file.

**Comment by tiwari-abhishek** [comment]
Ok, I see what you mean. I merged all customization into a single policy file and set its base policy as TrustFrameworkExtensions file. Additional files are deleted. Please check it out and and let me know if everything looks good.

**Pull request merged**
